import { BaseEntity, MoodCategory, TagSource } from '@/shared/types';

/**
 * Tag attached to a location — can be AI-generated or manually added.
 * Source: rules/features/location/flags.md Stories 4–5
 * DB: database-design.md §3.3 `location_tags`
 */
export interface LocationTag {
  /** Tag display name (normalized: lowercase, trimmed) */
  name: string;
  /** Whether the tag was generated by AI or manually by the user */
  source: TagSource;
  /** AI confidence score (0–1), only present for AI-generated tags */
  confidence?: number;
}

/**
 * Core location entity as returned from the API.
 * Source: rules/system.md §3.1 (required fields)
 * DB: database-design.md §3.2 `locations`
 */
export interface Location extends BaseEntity {
  /** Owner user ID */
  user_id: string;
  /** Location display name */
  name: string;
  /** Detailed description of the location */
  description: string | null;
  /** Cover image URL (Supabase Storage) */
  image_url: string | null;
  /** Latitude coordinate (-90 to 90) */
  latitude: number | null;
  /** Longitude coordinate (-180 to 180) */
  longitude: number | null;
  /** Whether the location is publicly visible */
  is_public: boolean;
  /** Associated mood category */
  mood_category: MoodCategory | null;
  /** Tags attached to this location */
  tags: LocationTag[];
}

/**
 * Lean location summary used in list views and AI context.
 * Only includes fields required by system.md §3.1.
 */
export interface LocationSummary {
  /** UUID */
  id: string;
  /** Location name */
  name: string;
  /** Tag names (string array for lean payloads) */
  tags: string[];
  /** Latitude */
  latitude: number | null;
  /** Longitude */
  longitude: number | null;
  /** Short description */
  description: string | null;
}

/**
 * Payload for creating a new location.
 * Source: rules/features/location/flags.md Story 1
 */
export interface CreateLocationPayload {
  /** Location name (required) */
  name: string;
  /** Description (optional) */
  description?: string;
  /** Cover image URL (optional) */
  image_url?: string;
  /** Latitude (optional, validated: -90 to 90) */
  latitude?: number;
  /** Longitude (optional, validated: -180 to 180) */
  longitude?: number;
  /** Mood category (optional) */
  mood_category?: MoodCategory;
  /** Whether the location is public (default: false) */
  is_public?: boolean;
  /** Manual tags to attach */
  tags?: string[];
}

/**
 * Payload for updating an existing location.
 * All fields are optional — only provided fields are updated.
 */
export interface UpdateLocationPayload extends Partial<CreateLocationPayload> {
  /** Location ID to update */
  id: string;
}

/**
 * Paginated response wrapper for location lists.
 */
export interface PaginatedLocations {
  /** Location items for the current page */
  data: Location[];
  /** Total count of locations matching the query */
  total: number;
  /** Current page number (0-indexed) */
  page: number;
  /** Number of items per page */
  limit: number;
  /** Whether more pages are available */
  hasMore: boolean;
}
