/**
 * Mood categories used across the application for mood matching,
 * tagging, and theme adaptation.
 * Source of truth: rules/design.md §2.3
 */
export type MoodCategory =
  | 'calm'
  | 'sad'
  | 'happy'
  | 'romantic'
  | 'energetic'
  | 'chill'
  | 'excited';

/**
 * Tag source identifier — whether a tag was generated by AI or added manually.
 * Source of truth: rules/features/location/flags.md Stories 4–5
 */
export type TagSource = 'manual' | 'ai';

/**
 * Visibility status for locations and profiles.
 */
export type Visibility = 'public' | 'private';

/**
 * Mood input method — text or emoji.
 * Source of truth: rules/features/mood-matching/flag.md Stories 5–6
 */
export type MoodInputType = 'text' | 'emoji';

/**
 * Map provider options.
 * Source: rules/system.md §1.1 — OpenFreeMap + MapLibre GL JS
 */
export type MapProvider = 'openfreemap';

/**
 * Base entity interface with common audit fields.
 */
export interface BaseEntity {
  /** Unique identifier (UUID v4) */
  id: string;
  /** ISO 8601 creation timestamp */
  created_at: string;
  /** ISO 8601 last update timestamp */
  updated_at: string;
}
