name: CI Unit Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        run: corepack enable && corepack prepare pnpm@9.6.0 --activate
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
  
      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test